[package]
name = "leaprs"
version = "0.1.0"
edition = "2021"

[dependencies]
leap-sys = "0.2"
num_enum = "0.5"
thiserror = "1"
bitflags = "1.3.2"

[build-dependencies]
copy_to_output = "2.0.0"

[workspace]
members = [
    "leaprs_testing",
]