name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  LEAPSDK_LIB_PATH: leap-sdk-redist/LeapSDK/lib/x64

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: gemini
        repository: plule/leap-sdk-redist
        token: ${{ secrets.LEAP_SDK_REDIST_PAT }}
        path: leap-sdk-redist
    - name: ls
      run: ls leap-sdk-redist
    - name: tree
      run: tree leap-sdk-redist
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build
    - name: Build Examples
      run: cargo build --examples
    - name: Build Tests
      run: cargo build --tests
    - name: Doc
      run: cargo doc
    - name: Style
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
    - name: Publish crate
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
